# SMOKE TEST FLOW

# 1. Create a profile
# @name createProfile
POST http://localhost:3000/profiles
Content-Type: application/json

{
  "name": "Smoke Test User",
  "description": "Verification of CRUD flow"
}

###

# Variable to store ID from previous request
@profileId = {{createProfile.response.body.id}}

# 2. Get the created profile by ID (uses the ID from step 1)
GET http://localhost:3000/profiles/{{profileId}}

###

# 3. Update the profile (uses the ID from step 1)
PUT http://localhost:3000/profiles/{{profileId}}
Content-Type: application/json

{
    "name" : "Updated Smoke User",
    "description" : "Updating details during smoke test"
}

###

# 4. Delete the profile (uses the ID from step 1)
DELETE http://localhost:3000/profiles/{{profileId}}

###

# UTILS

# Get all profiles
GET http://localhost:3000/profiles